apiVersion: v1
kind: Service
metadata:
    name: "myakscluster-6725"
    labels:
        app: "myakscluster-6725"
spec:
    type: ClusterIP
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: service
    - port: 8081
      targetPort: 8081
      name: management
    selector:
        app: "myakscluster-6725"